version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: met_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: met_art
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: met_api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: met_art
      DB_PORT: 3306
    ports:
      - "8000:8000"


  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: met_dashboard
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
volumes:
  mysql_data:
